set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN R1 [get_ports rst]
set_property PACKAGE_PIN P1 [get_ports button]
set_property PACKAGE_PIN W4 [get_ports switch[0]]
set_property PACKAGE_PIN R4 [get_ports switch[1]]
set_property PACKAGE_PIN T4 [get_ports switch[2]]
set_property PACKAGE_PIN T5 [get_ports switch[3]]
set_property PACKAGE_PIN U5 [get_ports switch[4]]
set_property PACKAGE_PIN W6 [get_ports switch[5]]
set_property PACKAGE_PIN W5 [get_ports switch[6]]
set_property PACKAGE_PIN U6 [get_ports switch[7]]
set_property PACKAGE_PIN A21 [get_ports led]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports switch[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[3]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[4]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[5]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[6]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[7]]
set_property IOSTANDARD LVCMOS33 [get_ports led]


