set_property PACKAGE_PIN Y18 [get_ports clk]
set_property PACKAGE_PIN R1 [get_ports rst]
set_property PACKAGE_PIN P1 [get_ports button]
set_property PACKAGE_PIN A21 [get_ports led[0]]
set_property PACKAGE_PIN E22 [get_ports led[1]]
set_property PACKAGE_PIN D22 [get_ports led[2]]
set_property PACKAGE_PIN E21 [get_ports led[3]]
set_property PACKAGE_PIN D21 [get_ports led[4]]
set_property PACKAGE_PIN G21 [get_ports led[5]]
set_property PACKAGE_PIN G22 [get_ports led[6]]
set_property PACKAGE_PIN F21 [get_ports led[7]]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property IOSTANDARD LVCMOS33 [get_ports led[7]]